export enum TipoPlaga {
  PULGONES = 'Pulgones',
  COCHINILLAS = 'Cochinillas',
  ACAROS = 'Acaros',
  MOSCA_BLANCA = 'Mosca Blanca ',
  INSECTOS_CUERPO_BLANDO = 'Insectos de cuerpo blando',
  HORMIGAS = 'Hormigas',
  HONGOS_MILDIU = 'Hongos mildiu y oídio',
  ESCAMAS = 'escamas',
  TRIPS = 'trips',
  ROYA = 'roya',
  MANCHA_NEGRA = 'Mancha negra',
  ORUGAS = 'Orugas',
  GUSANOS = 'Gusanos',
}
