version: "2.17.2"

services:
  plantopia:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000" 
    environment:
      PUERTO: 3000
      AMBIENTE: desarrollo
      VERSION: 0.1.0