services:
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./db/data_dev:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
    networks:
      - app-network

  devapi:
    image: node:22-alpine3.19
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    command: npm run start:dev
    restart: on-failure
    networks:
      - app-network
    user: root

  flyway:
    image: flyway/flyway:10.20.1-alpine
    container_name: flyway-migrator
    depends_on:
      - mysql
    entrypoint:
      [
        'flyway',
        '-url=jdbc:mysql://mysql:3306/${DB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false',
        '-user=${DB_USER}',
        '-password=${DB_PASS}',
        '-locations=filesystem:/flyway/sql',
         '-baselineOnMigrate=true',
        'migrate',
      ]
    volumes:
      - ./scripts_db:/flyway/sql # Mapea la carpeta de migraciones
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
    driver: bridge