services:
  mysql:
    image: 'mysql:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASS}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - /home/ubuntu/mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
    networks:
      - app-network

  flyway:
    image: flyway/flyway:10.20.1-alpine
    container_name: flyway-migrator
    depends_on:
      - mysql
    entrypoint:
      [
        'flyway',
        '-url=jdbc:mysql://mysql:3306/${DB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false',
        '-user=${DB_USER}',
        '-password=${DB_PASS}',
        '-locations=filesystem:/flyway/sql',
        '-baselineOnMigrate=true',
        'migrate',
      ]
    volumes:
      - ./scripts_db:/flyway/sql # Mapea la carpeta de migraciones
    networks:
      - app-network
    restart: on-failure
    command: -url=jdbc:mysql://mysql:3306/PlantopiaDB -user=user_prod -password=password_prod -connectRetries=5 repair migrate

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
