services:
  mysql:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: plantopiadb
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: password_dev
    volumes:
      - ./db/data_dev:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  devapi:
    image: node:22-alpine3.19
    working_dir: /usr/src/app
    volumes:
    - ./:/usr/src/app
    ports:
    - "3000:3000"
    depends_on:
    - mysql
    command:  npm run start:dev
    networks:
      - app-network
    user: root
networks:
  app-network:
    driver: bridge
