version: "2.17.2"

services:
  plantopia:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000" 
    environment:
      PUERTO: 7000
      AMBIENTE: produccion
      VERSION: 0.1.0