services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: plantopiadb
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: password_dev
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
