FROM node:20.15.1-slim

EXPOSE 3000

WORKDIR /app

ENV AMBIENTE=desarrollo
COPY package*.json /app/
COPY  ./.eslintrc.js /app/.eslintrc.js
COPY ./.gitignore /app/.gitignore
COPY ./.prettierrc /app/.prettierrc
COPY ./Logo-Green.png /app/Logo-Green.png
COPY ./nest-cli.json /app/nest-cli.json
COPY ./README.md /app/README.md
COPY ./tsconfig.build.json /app/tsconfig.build.json
COPY ./tsconfig.json /app/tsconfig.json
COPY ./src /app/src
COPY ./test /app/test
COPY ./.env.develop /app/.env.develop

RUN npm install
RUN npm install -g @nestjs/cli
RUN npm install --save @nestjs/common
RUN npm install --save @nestjs/core
RUN npm install --save @nestjs/typeorm typeorm mysql2
RUN npm install --save @nestjs/config
RUN npm install --save @nestjs/swagger
RUN npm install --save class-validator class-transformer
RUN npm install --save rxjs
RUN npm install --save express
RUN npm install --save @nestjs/mapped-types
RUN npm install --save @nestjs/mapped-types @nestjs/swagger
RUN npm install --save @nestjs/config @nestjs/core
RUN npm install --save-dev @types/node

CMD ["npm", "run", "start:dev"]