# Imagen node a utilizar
#FROM node:iron-slim
FROM node:22-alpine3.19

# Espera a que el servicio de la base de datos este disponible
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Exponer el puerto 3000
EXPOSE 3000

# Establece el directorio de trabajo
WORKDIR /app

# Establece la variable de entorno AMBIENTE
ENV AMBIENTE=desarrollo

# Copia el archivo package.json
COPY package*.json ./

# Establece el usuario root para no tener problemas con permisos
USER root

# Instala las dependencias
RUN npm install

# Copia el proyecto al directorio de trabajo
COPY . .

# Instala nest
#RUN npm install -g @nestjs/cli


# Ejecuta el proyecto
CMD npm run start:dev

#CMD ["npm", "run", "start:dev"]