services:
  plantopia:
    image: cnicolas86/plantopia:1.2.0
    container_name: plantopia-dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    env_file:
      - ../.env.develop
    environment:
      - AMBIENTE=desarrollo
    command: sh -c "npm install && npm run start:dev"

    networks:
      - app-network

    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: PlantopiaDB
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: password_dev
    volumes:
      -  ./db:/var/lib/mysql
    networks:
      - app-network
networks:
 app-network:
  driver: bridge
