services:
  plantopia:
    build:
      context: ..
      dockerfile: Dockerfile-dev
    container_name: plantopia-dev
    ports:
      - "3000:3000"
    volumes:
      - ../src:/app/src
    env_file:
      - ../.env.develop
    environment:
      - AMBIENTE=desarrollo
      - PATH=/usr/local/bin:/usr/local/sbin:/usr/sbin:/usr/bin:/sbin:/bin
    command: sh -c "/wait-for-it.sh mysql:3307 -- npm run start:dev"
    networks:
      - plantopiadev-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-dev
    ports:
      - "3307:3306"  # 3307 es el puerto local, 3306 es el puerto dentro del contenedor
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: plantopiadb
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: password_dev
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - plantopiadev-network

  flyway:
    image: flyway/flyway:10.20.1-alpine
    volumes:
      - ./scripts:/flyway/sql
    environment:
      HOST: mysql-dev
      PORT: 3306
      DB_NAME: plantopiadb
      DB_USER: user_dev
      DB_PASS: password_dev
    command: -url=jdbc:mysql://mysql:3306/plantopiadb -user=user_dev -password=password_dev -connectRetries=60 migrate
    depends_on:
      - mysql
    networks:
      - plantopiadev-network

networks:
  plantopiadev-network:
    driver: bridge

volumes:
  mysql-data: