services:
  plantopia:
    image: roancamo/plantopia:1.1.0
    container_name: plantopia-dev
    ports:
      - "3000:3000"  
    volumes:
      - ./src:/app/src 
    env_file:
      - .env.develop
    environment:
      - AMBIENTE=desarrollo 
    command: sh -c "npm install && npm run start:dev"