services:
  plantopia:
    image: cnicolas86/plantopia:1.4.0
    platform: linux/amd64
    container_name: plantopia-prod
    ports:
      - '4000:4000'
    env_file:
      - ./.env.productivo
    depends_on:
      - mysql
      - flyway
    restart: on-failure
    networks:
      - plantopia-network
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads

  mysql:
    image: mysql:8.0
    container_name: mysql-prod
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: PlantopiaDB
      MYSQL_USER: user_prod
      MYSQL_PASSWORD: password_prod
    volumes:
      - /home/ubuntu/mysql_data:/var/lib/mysql
    restart: always
    networks:
      - plantopia-network

  flyway:
    image: flyway/flyway
    volumes:
      - ./scripts_db:/flyway/sql
    environment:
      HOST: mysql-prod
      PORT: 3306
      DB_NAME: PlantopiaDB
      DB_USER: user_prod
      DB_PASS: password_prod
      FLYWAY_BASELINE_ON_MIGRATE: 'true'
    command: -url=jdbc:mysql://mysql:3306/PlantopiaDB -user=user_prod -password=password_prod -connectRetries=5 migrate
    depends_on:
      - mysql
    networks:
      - plantopia-network

networks:
  plantopia-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
