services:
  plantopia:
    image: cnicolas86/plantopia:1.2.0
    platform: linux/amd64
    container_name: plantopia-prod
    ports:
      - "4000:4000"
    env_file:
      - ../.env.productivo
    depends_on:
      - mysql
      - flyway
    networks:
      - plantopia-network

  mysql:
    image: mysql:8.0
    container_name: mysql-prod
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: PlantopiaDB
      MYSQL_USER: user_prod
      MYSQL_PASSWORD: password_prod
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - plantopia-network

  flyway:
    image: flyway/flyway:10.20.1-alpine
    volumes:
      - ./scripts:/flyway/sql
    environment:
      HOST: mysql-prod
      PORT: 3306
      DB_NAME: PlantopiaDB
      DB_USER: user_prod
      DB_PASS: password_prod
    command: -url=jdbc:mysql://mysql:3306/PlantopiaDB -user=user_prod -password=password_prod -connectRetries=60 migrate
    depends_on:
      - mysql
    networks:
      - plantopia-network

networks:
  plantopia-network:
    driver: bridge

volumes:
  mysql-data: