export enum ComposicionSustrato {
  PERLITA = 'Perlita',
  TURBA = 'Turba',
  VERMICULITA = 'Vermiculita',
  FIBRA_COCO = 'Fibra de Coco',
  ARENA = 'Arena',
  CORTEZA_PINO = 'Corteza de pino',
  CARBON_VEGETAL = 'Carbón Vegetal',
  GRAVA = 'Grava',
  HUMMUS = 'Hummus',
  COMPOST = 'Compost',
  MATERIAORGANICA = 'MateriaOrganica',
  CORTEZA = 'Corteza',
  ARENA_VOLCANICA = 'ArenaVolcanica',
}
