export enum TexturaSustrato {
  LIGERO = 'Ligero',
  AIREADO = 'Aireado',
  ESPONJOSO = 'Esponjoso',
  UNIVERSAL = 'Universal',
  SUAVE = 'Suave',
  LIGERAMENTE_ARENOSO = 'Ligeramente arenoso',
  RICO_NUTRIENTES = 'rico en nutrientes',
  GRUESO = 'Grueso',
  ARENOSO = 'Arenoso',
  SUELTO = 'Suelto',
  ESPONOJOSO = 'Esponjoso',
  DENSO = 'Denso',
  RICO = 'rico',
  MEDIO = 'Medio',
  FINA = 'Fina',
}
